version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8888:8888"
    volumes:
      - /etc/python-env/parsing_project:/app/.env
    restart: unless-stopped

